apiVersion: v1
kind: ConfigMap

metadata:
  name: postgreSQL-config
  namespace: dbcon

data:
  APP_NAME: "postgreSQL-Demo"
  ENVIRONMENT: "dbcon"
  MESSAGE: "Welcome to postgreSQL-Demo Application from ConfigMap on 0616"
