apiVersion: v1
kind: ConfigMap

metadata:
  name: postgresql-config
  namespace: dbcon

data:
  APP_NAME: "postgresql-Demo"
  ENVIRONMENT: "dbcon"
  MESSAGE: "Welcome to postgresql-Demo Application from ConfigMap on 0616"
