apiVersion: v1
kind: ConfigMap

metadata:
  name: flash-config
  namespace: test

data:
  APP_NAME: "Flash-Demo"
  ENVIRONMENT: "Test"
  MESSAGE: "Welcome to Flash-Demo Application from ConfigMap on 0616"
